### ISSUE TITLE
Failed to activate the linter-julia package

### ISSUE THREAD

**Issue by kazumiyamada** [TeroFrondelius/linter-julia#18]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.2 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [linter-julia](https://github.com/TeroFrondelius/linter-julia) package 0.2.0

### Stack Trace

Failed to activate the linter-julia package

```
At Bad argument

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at exports.spawn (child_process.js:392:9)
    at Object.activate (/packages/linter-julia/lib/linter-julia.coffee:83:15)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:439:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:69:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:303:11)
    at /app.asar/src/buffered-process.js:316:11
    at /app.asar/src/buffered-process.js:185:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -0:52.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
block-comment-plus 0.4.0 
Hydrogen 1.5.5 
ink 0.6.3 
julia-client 0.5.12 
julia-ide 0.3.0 
language-julia 0.10.0 
linter-julia 0.2.0 
script 3.14.1 
tool-bar 1.0.1 
uber-juno 0.1.1 
```

**Comment by TeroFrondelius** [comment]
@kazumiyamada can you share what you have in the settings (Ctrl + ,). I tested on my mint with default and absolute path and both of them works: 
![screenshot from 2017-02-17 17 05 14](https://cloud.githubusercontent.com/assets/12501534/23070372/a28faa08-f533-11e6-9412-d9b6eefc5bbd.png)

![screenshot from 2017-02-17 17 04 53](https://cloud.githubusercontent.com/assets/12501534/23070387/ae59ed4e-f533-11e6-8791-d496bfc3c1b8.png)

**Comment by TeroFrondelius** [comment]
This should have been fixed now. If not, please open another issue after updating to latest release.
